quicksort : quick_sort.cpp
		g++ -o quicksort quick_sort.cpp -std=c++11
mergesort : merge_sort.cpp
		g++ -o mergesort merge_sort.cpp -std=c++11
insertionsort : insertion_sort.cpp
		g++ -o insertionsort insertion_sort.cpp -std=c++11
countingsort : counting_sort.cpp
		g++ -o countingsort counting_sort.cpp -std=c++11
